/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 52139aaf367e8e8fc35cc39cda41a28c)
interface __BaseEnv_Env {
	CLOUDFLARE_ACCOUNT_ID: "78109ec18c7c85b194b19fb32e3bb149";
	LANGUAGE_ID_BASIC: DurableObjectNamespace<import("./src/server").LanguageIdBasicContainer>;
	LANGUAGE_ID_STANDARD: DurableObjectNamespace<import("./src/server").LanguageIdStandardContainer>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "LanguageIdBasicContainer" | "LanguageIdStandardContainer";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CLOUDFLARE_ACCOUNT_ID">> {}
}
