/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: dc34e92e8422259553617957353240f4)
interface __BaseEnv_Env {
	AI: Ai;
	CLOUDFLARE_ACCOUNT_ID: "78109ec18c7c85b194b19fb32e3bb149";
	SPEECHBRAIN_ECAPA_BASIC: DurableObjectNamespace<import("./src/server").SpeechbrainEcapaBasicContainer>;
	SPEECHBRAIN_ECAPA_STANDARD: DurableObjectNamespace<import("./src/server").SpeechbrainEcapaStandardContainer>;
	NVIDIA_AMBERNET_BASIC: DurableObjectNamespace<import("./src/server").NvidiaAmbernetBasicContainer>;
	NVIDIA_AMBERNET_STANDARD: DurableObjectNamespace<import("./src/server").NvidiaAmbernetStandardContainer>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "SpeechbrainEcapaBasicContainer" | "SpeechbrainEcapaStandardContainer" | "NvidiaAmbernetBasicContainer" | "NvidiaAmbernetStandardContainer";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CLOUDFLARE_ACCOUNT_ID">> {}
}
