// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 1811000938;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_kotoba_beacon_companion',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  List<AzooKeyModel> crateApiSimpleAllAzookeyModels();

  List<PipelineRoute> crateApiSimpleAllPipelineRoutes();

  Future<AzooKeyOutput> crateApiSimpleConvertAzookey({required String reading});

  DesktopCommand crateApiSimpleDecodeDesktopCommand({required String json});

  Future<BigInt> crateApiSimpleDecodeDiscoveryRequest({required String json});

  DiscoveryResponse crateApiSimpleDecodeDiscoveryResponse({
    required String json,
  });

  PipelineRoute crateApiSimpleDecodeMobileRouteRequest({required String json});

  MobileStageResult crateApiSimpleDecodeMobileStageResult({
    required String json,
  });

  PairRequest crateApiSimpleDecodePairRequest({required String json});

  SessionConfiguration crateApiSimpleDecodeSessionConfiguration({
    required String json,
  });

  AzooKeyModel crateApiSimpleDefaultAzookeyModel();

  PipelineRoute crateApiSimpleDefaultPipelineRoute();

  String crateApiSimpleEncodeAudioBoundary({
    required String messageType,
    required String sessionId,
    required BigInt turnId,
    required BigInt revision,
  });

  String crateApiSimpleEncodeDiscoveryRequest({required BigInt nonce});

  Future<String> crateApiSimpleEncodeDiscoveryResponse({
    required BigInt nonce,
    required String endpoint,
    required String token,
  });

  String crateApiSimpleEncodePairRequest({
    required String token,
    required String deviceId,
    required String deviceName,
  });

  String crateApiSimpleEncodeRouteConfiguration({required PipelineRoute route});

  String crateApiSimpleEncodeRouteRequest({required PipelineRoute route});

  String crateApiSimpleEncodeSessionConfigure({
    required String sessionId,
    required PipelineRoute route,
    required MobileCapabilities capabilities,
  });

  String crateApiSimpleEncodeSessionReady({
    required String sessionId,
    required PipelineRoute route,
  });

  String crateApiSimpleEncodeStageRequest({
    required String messageType,
    required String sessionId,
    required BigInt turnId,
    required BigInt revision,
    required String text,
    required bool isFinal,
  });

  String crateApiSimpleEncodeStageResult({
    required ProcessingStage stage,
    required String sessionId,
    required BigInt turnId,
    required BigInt revision,
    required String text,
    required bool isFinal,
  });

  String crateApiSimpleEncodeTranslationEnabled({
    required String sessionId,
    required bool enabled,
  });

  Future<void> crateApiSimpleInitApp();

  Future<void> crateApiSimpleInitializeAzookeyDictionary({
    required List<int> bytes,
  });

  Future<PipelineRoute> crateApiSimpleMobileCapabilitiesConstrain({
    required MobileCapabilities that,
    required PipelineRoute route,
  });

  Future<bool> crateApiSimpleMobileCapabilitiesSupports({
    required MobileCapabilities that,
    required ProcessingStage stage,
  });

  String crateApiSimplePipelineRouteId({required PipelineRoute route});

  Future<void> crateApiSimplePrepareAzookeyModel({
    required AzooKeyModel model,
    required String modelPath,
    required String tokenizerDirectory,
  });

  Future<void> crateApiSimplePrepareMobileRustAsr({
    required String modelDirectory,
  });

  Future<void> crateApiSimplePrepareQuickmtTranslation({
    required String modelDirectory,
  });

  Future<void> crateApiSimpleReleaseAzookeyDictionary();

  Future<void> crateApiSimpleReleaseAzookeyModel();

  Future<void> crateApiSimpleReleaseMobileRustAsr();

  Future<void> crateApiSimpleReleaseQuickmtTranslation();

  bool crateApiSimpleShouldContinueOnMobile({
    required PipelineRoute route,
    required ProcessingStage completedStage,
  });

  ExecutionDevice crateApiSimpleStageOwner({
    required PipelineRoute route,
    required ProcessingStage stage,
  });

  Future<String> crateApiSimpleTranscribeMobileRustAsr({
    required List<int> pcm16,
  });

  Future<String> crateApiSimpleTranslateQuickmt({required String text});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  List<AzooKeyModel> crateApiSimpleAllAzookeyModels() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_azoo_key_model,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleAllAzookeyModelsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleAllAzookeyModelsConstMeta =>
      const TaskConstMeta(
        debugName: "all_azookey_models",
        argNames: [],
      );

  @override
  List<PipelineRoute> crateApiSimpleAllPipelineRoutes() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_pipeline_route,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleAllPipelineRoutesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleAllPipelineRoutesConstMeta =>
      const TaskConstMeta(
        debugName: "all_pipeline_routes",
        argNames: [],
      );

  @override
  Future<AzooKeyOutput> crateApiSimpleConvertAzookey({
    required String reading,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(reading, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_azoo_key_output,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleConvertAzookeyConstMeta,
        argValues: [reading],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleConvertAzookeyConstMeta =>
      const TaskConstMeta(
        debugName: "convert_azookey",
        argNames: ["reading"],
      );

  @override
  DesktopCommand crateApiSimpleDecodeDesktopCommand({required String json}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(json, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_desktop_command,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleDecodeDesktopCommandConstMeta,
        argValues: [json],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleDecodeDesktopCommandConstMeta =>
      const TaskConstMeta(
        debugName: "decode_desktop_command",
        argNames: ["json"],
      );

  @override
  Future<BigInt> crateApiSimpleDecodeDiscoveryRequest({required String json}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(json, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleDecodeDiscoveryRequestConstMeta,
        argValues: [json],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleDecodeDiscoveryRequestConstMeta =>
      const TaskConstMeta(
        debugName: "decode_discovery_request",
        argNames: ["json"],
      );

  @override
  DiscoveryResponse crateApiSimpleDecodeDiscoveryResponse({
    required String json,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(json, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_discovery_response,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleDecodeDiscoveryResponseConstMeta,
        argValues: [json],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleDecodeDiscoveryResponseConstMeta =>
      const TaskConstMeta(
        debugName: "decode_discovery_response",
        argNames: ["json"],
      );

  @override
  PipelineRoute crateApiSimpleDecodeMobileRouteRequest({required String json}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(json, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_pipeline_route,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleDecodeMobileRouteRequestConstMeta,
        argValues: [json],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleDecodeMobileRouteRequestConstMeta =>
      const TaskConstMeta(
        debugName: "decode_mobile_route_request",
        argNames: ["json"],
      );

  @override
  MobileStageResult crateApiSimpleDecodeMobileStageResult({
    required String json,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(json, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_mobile_stage_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleDecodeMobileStageResultConstMeta,
        argValues: [json],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleDecodeMobileStageResultConstMeta =>
      const TaskConstMeta(
        debugName: "decode_mobile_stage_result",
        argNames: ["json"],
      );

  @override
  PairRequest crateApiSimpleDecodePairRequest({required String json}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(json, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_pair_request,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleDecodePairRequestConstMeta,
        argValues: [json],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleDecodePairRequestConstMeta =>
      const TaskConstMeta(
        debugName: "decode_pair_request",
        argNames: ["json"],
      );

  @override
  SessionConfiguration crateApiSimpleDecodeSessionConfiguration({
    required String json,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(json, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_session_configuration,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleDecodeSessionConfigurationConstMeta,
        argValues: [json],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleDecodeSessionConfigurationConstMeta =>
      const TaskConstMeta(
        debugName: "decode_session_configuration",
        argNames: ["json"],
      );

  @override
  AzooKeyModel crateApiSimpleDefaultAzookeyModel() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_azoo_key_model,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleDefaultAzookeyModelConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleDefaultAzookeyModelConstMeta =>
      const TaskConstMeta(
        debugName: "default_azookey_model",
        argNames: [],
      );

  @override
  PipelineRoute crateApiSimpleDefaultPipelineRoute() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_pipeline_route,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleDefaultPipelineRouteConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleDefaultPipelineRouteConstMeta =>
      const TaskConstMeta(
        debugName: "default_pipeline_route",
        argNames: [],
      );

  @override
  String crateApiSimpleEncodeAudioBoundary({
    required String messageType,
    required String sessionId,
    required BigInt turnId,
    required BigInt revision,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(messageType, serializer);
          sse_encode_String(sessionId, serializer);
          sse_encode_u_64(turnId, serializer);
          sse_encode_u_64(revision, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleEncodeAudioBoundaryConstMeta,
        argValues: [messageType, sessionId, turnId, revision],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleEncodeAudioBoundaryConstMeta =>
      const TaskConstMeta(
        debugName: "encode_audio_boundary",
        argNames: ["messageType", "sessionId", "turnId", "revision"],
      );

  @override
  String crateApiSimpleEncodeDiscoveryRequest({required BigInt nonce}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(nonce, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleEncodeDiscoveryRequestConstMeta,
        argValues: [nonce],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleEncodeDiscoveryRequestConstMeta =>
      const TaskConstMeta(
        debugName: "encode_discovery_request",
        argNames: ["nonce"],
      );

  @override
  Future<String> crateApiSimpleEncodeDiscoveryResponse({
    required BigInt nonce,
    required String endpoint,
    required String token,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(nonce, serializer);
          sse_encode_String(endpoint, serializer);
          sse_encode_String(token, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleEncodeDiscoveryResponseConstMeta,
        argValues: [nonce, endpoint, token],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleEncodeDiscoveryResponseConstMeta =>
      const TaskConstMeta(
        debugName: "encode_discovery_response",
        argNames: ["nonce", "endpoint", "token"],
      );

  @override
  String crateApiSimpleEncodePairRequest({
    required String token,
    required String deviceId,
    required String deviceName,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(token, serializer);
          sse_encode_String(deviceId, serializer);
          sse_encode_String(deviceName, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleEncodePairRequestConstMeta,
        argValues: [token, deviceId, deviceName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleEncodePairRequestConstMeta =>
      const TaskConstMeta(
        debugName: "encode_pair_request",
        argNames: ["token", "deviceId", "deviceName"],
      );

  @override
  String crateApiSimpleEncodeRouteConfiguration({
    required PipelineRoute route,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_pipeline_route(route, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleEncodeRouteConfigurationConstMeta,
        argValues: [route],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleEncodeRouteConfigurationConstMeta =>
      const TaskConstMeta(
        debugName: "encode_route_configuration",
        argNames: ["route"],
      );

  @override
  String crateApiSimpleEncodeRouteRequest({required PipelineRoute route}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_pipeline_route(route, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleEncodeRouteRequestConstMeta,
        argValues: [route],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleEncodeRouteRequestConstMeta =>
      const TaskConstMeta(
        debugName: "encode_route_request",
        argNames: ["route"],
      );

  @override
  String crateApiSimpleEncodeSessionConfigure({
    required String sessionId,
    required PipelineRoute route,
    required MobileCapabilities capabilities,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_box_autoadd_pipeline_route(route, serializer);
          sse_encode_box_autoadd_mobile_capabilities(capabilities, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleEncodeSessionConfigureConstMeta,
        argValues: [sessionId, route, capabilities],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleEncodeSessionConfigureConstMeta =>
      const TaskConstMeta(
        debugName: "encode_session_configure",
        argNames: ["sessionId", "route", "capabilities"],
      );

  @override
  String crateApiSimpleEncodeSessionReady({
    required String sessionId,
    required PipelineRoute route,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_box_autoadd_pipeline_route(route, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleEncodeSessionReadyConstMeta,
        argValues: [sessionId, route],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleEncodeSessionReadyConstMeta =>
      const TaskConstMeta(
        debugName: "encode_session_ready",
        argNames: ["sessionId", "route"],
      );

  @override
  String crateApiSimpleEncodeStageRequest({
    required String messageType,
    required String sessionId,
    required BigInt turnId,
    required BigInt revision,
    required String text,
    required bool isFinal,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(messageType, serializer);
          sse_encode_String(sessionId, serializer);
          sse_encode_u_64(turnId, serializer);
          sse_encode_u_64(revision, serializer);
          sse_encode_String(text, serializer);
          sse_encode_bool(isFinal, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleEncodeStageRequestConstMeta,
        argValues: [messageType, sessionId, turnId, revision, text, isFinal],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleEncodeStageRequestConstMeta =>
      const TaskConstMeta(
        debugName: "encode_stage_request",
        argNames: [
          "messageType",
          "sessionId",
          "turnId",
          "revision",
          "text",
          "isFinal",
        ],
      );

  @override
  String crateApiSimpleEncodeStageResult({
    required ProcessingStage stage,
    required String sessionId,
    required BigInt turnId,
    required BigInt revision,
    required String text,
    required bool isFinal,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_processing_stage(stage, serializer);
          sse_encode_String(sessionId, serializer);
          sse_encode_u_64(turnId, serializer);
          sse_encode_u_64(revision, serializer);
          sse_encode_String(text, serializer);
          sse_encode_bool(isFinal, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleEncodeStageResultConstMeta,
        argValues: [stage, sessionId, turnId, revision, text, isFinal],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleEncodeStageResultConstMeta =>
      const TaskConstMeta(
        debugName: "encode_stage_result",
        argNames: [
          "stage",
          "sessionId",
          "turnId",
          "revision",
          "text",
          "isFinal",
        ],
      );

  @override
  String crateApiSimpleEncodeTranslationEnabled({
    required String sessionId,
    required bool enabled,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_bool(enabled, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleEncodeTranslationEnabledConstMeta,
        argValues: [sessionId, enabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleEncodeTranslationEnabledConstMeta =>
      const TaskConstMeta(
        debugName: "encode_translation_enabled",
        argNames: ["sessionId", "enabled"],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta => const TaskConstMeta(
    debugName: "init_app",
    argNames: [],
  );

  @override
  Future<void> crateApiSimpleInitializeAzookeyDictionary({
    required List<int> bytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleInitializeAzookeyDictionaryConstMeta,
        argValues: [bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitializeAzookeyDictionaryConstMeta =>
      const TaskConstMeta(
        debugName: "initialize_azookey_dictionary",
        argNames: ["bytes"],
      );

  @override
  Future<PipelineRoute> crateApiSimpleMobileCapabilitiesConstrain({
    required MobileCapabilities that,
    required PipelineRoute route,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_mobile_capabilities(that, serializer);
          sse_encode_box_autoadd_pipeline_route(route, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_pipeline_route,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleMobileCapabilitiesConstrainConstMeta,
        argValues: [that, route],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMobileCapabilitiesConstrainConstMeta =>
      const TaskConstMeta(
        debugName: "mobile_capabilities_constrain",
        argNames: ["that", "route"],
      );

  @override
  Future<bool> crateApiSimpleMobileCapabilitiesSupports({
    required MobileCapabilities that,
    required ProcessingStage stage,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_mobile_capabilities(that, serializer);
          sse_encode_processing_stage(stage, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleMobileCapabilitiesSupportsConstMeta,
        argValues: [that, stage],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMobileCapabilitiesSupportsConstMeta =>
      const TaskConstMeta(
        debugName: "mobile_capabilities_supports",
        argNames: ["that", "stage"],
      );

  @override
  String crateApiSimplePipelineRouteId({required PipelineRoute route}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_pipeline_route(route, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimplePipelineRouteIdConstMeta,
        argValues: [route],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimplePipelineRouteIdConstMeta =>
      const TaskConstMeta(
        debugName: "pipeline_route_id",
        argNames: ["route"],
      );

  @override
  Future<void> crateApiSimplePrepareAzookeyModel({
    required AzooKeyModel model,
    required String modelPath,
    required String tokenizerDirectory,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_azoo_key_model(model, serializer);
          sse_encode_String(modelPath, serializer);
          sse_encode_String(tokenizerDirectory, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimplePrepareAzookeyModelConstMeta,
        argValues: [model, modelPath, tokenizerDirectory],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimplePrepareAzookeyModelConstMeta =>
      const TaskConstMeta(
        debugName: "prepare_azookey_model",
        argNames: ["model", "modelPath", "tokenizerDirectory"],
      );

  @override
  Future<void> crateApiSimplePrepareMobileRustAsr({
    required String modelDirectory,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(modelDirectory, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimplePrepareMobileRustAsrConstMeta,
        argValues: [modelDirectory],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimplePrepareMobileRustAsrConstMeta =>
      const TaskConstMeta(
        debugName: "prepare_mobile_rust_asr",
        argNames: ["modelDirectory"],
      );

  @override
  Future<void> crateApiSimplePrepareQuickmtTranslation({
    required String modelDirectory,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(modelDirectory, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimplePrepareQuickmtTranslationConstMeta,
        argValues: [modelDirectory],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimplePrepareQuickmtTranslationConstMeta =>
      const TaskConstMeta(
        debugName: "prepare_quickmt_translation",
        argNames: ["modelDirectory"],
      );

  @override
  Future<void> crateApiSimpleReleaseAzookeyDictionary() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleReleaseAzookeyDictionaryConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleReleaseAzookeyDictionaryConstMeta =>
      const TaskConstMeta(
        debugName: "release_azookey_dictionary",
        argNames: [],
      );

  @override
  Future<void> crateApiSimpleReleaseAzookeyModel() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleReleaseAzookeyModelConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleReleaseAzookeyModelConstMeta =>
      const TaskConstMeta(
        debugName: "release_azookey_model",
        argNames: [],
      );

  @override
  Future<void> crateApiSimpleReleaseMobileRustAsr() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleReleaseMobileRustAsrConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleReleaseMobileRustAsrConstMeta =>
      const TaskConstMeta(
        debugName: "release_mobile_rust_asr",
        argNames: [],
      );

  @override
  Future<void> crateApiSimpleReleaseQuickmtTranslation() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 35,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleReleaseQuickmtTranslationConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleReleaseQuickmtTranslationConstMeta =>
      const TaskConstMeta(
        debugName: "release_quickmt_translation",
        argNames: [],
      );

  @override
  bool crateApiSimpleShouldContinueOnMobile({
    required PipelineRoute route,
    required ProcessingStage completedStage,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_pipeline_route(route, serializer);
          sse_encode_processing_stage(completedStage, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 36)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleShouldContinueOnMobileConstMeta,
        argValues: [route, completedStage],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleShouldContinueOnMobileConstMeta =>
      const TaskConstMeta(
        debugName: "should_continue_on_mobile",
        argNames: ["route", "completedStage"],
      );

  @override
  ExecutionDevice crateApiSimpleStageOwner({
    required PipelineRoute route,
    required ProcessingStage stage,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_pipeline_route(route, serializer);
          sse_encode_processing_stage(stage, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 37)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_execution_device,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleStageOwnerConstMeta,
        argValues: [route, stage],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleStageOwnerConstMeta => const TaskConstMeta(
    debugName: "stage_owner",
    argNames: ["route", "stage"],
  );

  @override
  Future<String> crateApiSimpleTranscribeMobileRustAsr({
    required List<int> pcm16,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(pcm16, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 38,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleTranscribeMobileRustAsrConstMeta,
        argValues: [pcm16],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleTranscribeMobileRustAsrConstMeta =>
      const TaskConstMeta(
        debugName: "transcribe_mobile_rust_asr",
        argNames: ["pcm16"],
      );

  @override
  Future<String> crateApiSimpleTranslateQuickmt({required String text}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 39,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleTranslateQuickmtConstMeta,
        argValues: [text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleTranslateQuickmtConstMeta =>
      const TaskConstMeta(
        debugName: "translate_quickmt",
        argNames: ["text"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AzooKeyModel dco_decode_azoo_key_model(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AzooKeyModel.values[raw as int];
  }

  @protected
  AzooKeyOutput dco_decode_azoo_key_output(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return AzooKeyOutput(
      text: dco_decode_String(arr[0]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  MobileCapabilities dco_decode_box_autoadd_mobile_capabilities(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_mobile_capabilities(raw);
  }

  @protected
  PipelineRoute dco_decode_box_autoadd_pipeline_route(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_pipeline_route(raw);
  }

  @protected
  DesktopCommand dco_decode_desktop_command(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return DesktopCommand_SessionReady(
          sessionId: dco_decode_String(raw[1]),
          route: dco_decode_box_autoadd_pipeline_route(raw[2]),
        );
      case 1:
        return DesktopCommand_ConfigureRoute(
          route: dco_decode_box_autoadd_pipeline_route(raw[1]),
        );
      case 2:
        return DesktopCommand_StartAudio(
          sessionId: dco_decode_String(raw[1]),
          turnId: dco_decode_u_64(raw[2]),
          revision: dco_decode_u_64(raw[3]),
        );
      case 3:
        return DesktopCommand_EndAudio(
          sessionId: dco_decode_String(raw[1]),
          turnId: dco_decode_u_64(raw[2]),
          revision: dco_decode_u_64(raw[3]),
        );
      case 4:
        return DesktopCommand_RunAzookey(
          sessionId: dco_decode_String(raw[1]),
          turnId: dco_decode_u_64(raw[2]),
          revision: dco_decode_u_64(raw[3]),
          text: dco_decode_String(raw[4]),
          isFinal: dco_decode_bool(raw[5]),
        );
      case 5:
        return DesktopCommand_RunTranslation(
          sessionId: dco_decode_String(raw[1]),
          turnId: dco_decode_u_64(raw[2]),
          revision: dco_decode_u_64(raw[3]),
          sourceText: dco_decode_String(raw[4]),
          isFinal: dco_decode_bool(raw[5]),
        );
      case 6:
        return DesktopCommand_StopSession(
          sessionId: dco_decode_String(raw[1]),
        );
      case 7:
        return DesktopCommand_SetTranslationEnabled(
          enabled: dco_decode_bool(raw[1]),
        );
      case 8:
        return DesktopCommand_Ping(
          nonce: dco_decode_u_64(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  DiscoveryResponse dco_decode_discovery_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DiscoveryResponse(
      nonce: dco_decode_u_64(arr[0]),
      endpoint: dco_decode_String(arr[1]),
      token: dco_decode_String(arr[2]),
    );
  }

  @protected
  ExecutionDevice dco_decode_execution_device(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ExecutionDevice.values[raw as int];
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<AzooKeyModel> dco_decode_list_azoo_key_model(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_azoo_key_model).toList();
  }

  @protected
  List<PipelineRoute> dco_decode_list_pipeline_route(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_pipeline_route).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MobileCapabilities dco_decode_mobile_capabilities(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return MobileCapabilities(
      deviceId: dco_decode_String(arr[0]),
      deviceName: dco_decode_String(arr[1]),
      platform: dco_decode_String(arr[2]),
      asrAvailable: dco_decode_bool(arr[3]),
      azookeyAvailable: dco_decode_bool(arr[4]),
      translationAvailable: dco_decode_bool(arr[5]),
    );
  }

  @protected
  MobileStageResult dco_decode_mobile_stage_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return MobileStageResult(
      messageType: dco_decode_String(arr[0]),
      sessionId: dco_decode_String(arr[1]),
      turnId: dco_decode_u_64(arr[2]),
      revision: dco_decode_u_64(arr[3]),
      text: dco_decode_String(arr[4]),
      isFinal: dco_decode_bool(arr[5]),
    );
  }

  @protected
  PairRequest dco_decode_pair_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return PairRequest(
      token: dco_decode_String(arr[0]),
      deviceId: dco_decode_String(arr[1]),
      deviceName: dco_decode_String(arr[2]),
    );
  }

  @protected
  PipelineRoute dco_decode_pipeline_route(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return PipelineRoute(
      asr: dco_decode_execution_device(arr[0]),
      azookey: dco_decode_execution_device(arr[1]),
      translation: dco_decode_execution_device(arr[2]),
    );
  }

  @protected
  ProcessingStage dco_decode_processing_stage(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ProcessingStage.values[raw as int];
  }

  @protected
  SessionConfiguration dco_decode_session_configuration(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SessionConfiguration(
      sessionId: dco_decode_String(arr[0]),
      route: dco_decode_pipeline_route(arr[1]),
      capabilities: dco_decode_mobile_capabilities(arr[2]),
    );
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AzooKeyModel sse_decode_azoo_key_model(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return AzooKeyModel.values[inner];
  }

  @protected
  AzooKeyOutput sse_decode_azoo_key_output(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_text = sse_decode_String(deserializer);
    return AzooKeyOutput(text: var_text);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  MobileCapabilities sse_decode_box_autoadd_mobile_capabilities(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_mobile_capabilities(deserializer));
  }

  @protected
  PipelineRoute sse_decode_box_autoadd_pipeline_route(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_pipeline_route(deserializer));
  }

  @protected
  DesktopCommand sse_decode_desktop_command(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_sessionId = sse_decode_String(deserializer);
        var var_route = sse_decode_box_autoadd_pipeline_route(deserializer);
        return DesktopCommand_SessionReady(
          sessionId: var_sessionId,
          route: var_route,
        );
      case 1:
        var var_route = sse_decode_box_autoadd_pipeline_route(deserializer);
        return DesktopCommand_ConfigureRoute(route: var_route);
      case 2:
        var var_sessionId = sse_decode_String(deserializer);
        var var_turnId = sse_decode_u_64(deserializer);
        var var_revision = sse_decode_u_64(deserializer);
        return DesktopCommand_StartAudio(
          sessionId: var_sessionId,
          turnId: var_turnId,
          revision: var_revision,
        );
      case 3:
        var var_sessionId = sse_decode_String(deserializer);
        var var_turnId = sse_decode_u_64(deserializer);
        var var_revision = sse_decode_u_64(deserializer);
        return DesktopCommand_EndAudio(
          sessionId: var_sessionId,
          turnId: var_turnId,
          revision: var_revision,
        );
      case 4:
        var var_sessionId = sse_decode_String(deserializer);
        var var_turnId = sse_decode_u_64(deserializer);
        var var_revision = sse_decode_u_64(deserializer);
        var var_text = sse_decode_String(deserializer);
        var var_isFinal = sse_decode_bool(deserializer);
        return DesktopCommand_RunAzookey(
          sessionId: var_sessionId,
          turnId: var_turnId,
          revision: var_revision,
          text: var_text,
          isFinal: var_isFinal,
        );
      case 5:
        var var_sessionId = sse_decode_String(deserializer);
        var var_turnId = sse_decode_u_64(deserializer);
        var var_revision = sse_decode_u_64(deserializer);
        var var_sourceText = sse_decode_String(deserializer);
        var var_isFinal = sse_decode_bool(deserializer);
        return DesktopCommand_RunTranslation(
          sessionId: var_sessionId,
          turnId: var_turnId,
          revision: var_revision,
          sourceText: var_sourceText,
          isFinal: var_isFinal,
        );
      case 6:
        var var_sessionId = sse_decode_String(deserializer);
        return DesktopCommand_StopSession(sessionId: var_sessionId);
      case 7:
        var var_enabled = sse_decode_bool(deserializer);
        return DesktopCommand_SetTranslationEnabled(enabled: var_enabled);
      case 8:
        var var_nonce = sse_decode_u_64(deserializer);
        return DesktopCommand_Ping(nonce: var_nonce);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  DiscoveryResponse sse_decode_discovery_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_nonce = sse_decode_u_64(deserializer);
    var var_endpoint = sse_decode_String(deserializer);
    var var_token = sse_decode_String(deserializer);
    return DiscoveryResponse(
      nonce: var_nonce,
      endpoint: var_endpoint,
      token: var_token,
    );
  }

  @protected
  ExecutionDevice sse_decode_execution_device(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ExecutionDevice.values[inner];
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<AzooKeyModel> sse_decode_list_azoo_key_model(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AzooKeyModel>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_azoo_key_model(deserializer));
    }
    return ans_;
  }

  @protected
  List<PipelineRoute> sse_decode_list_pipeline_route(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PipelineRoute>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_pipeline_route(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MobileCapabilities sse_decode_mobile_capabilities(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_deviceId = sse_decode_String(deserializer);
    var var_deviceName = sse_decode_String(deserializer);
    var var_platform = sse_decode_String(deserializer);
    var var_asrAvailable = sse_decode_bool(deserializer);
    var var_azookeyAvailable = sse_decode_bool(deserializer);
    var var_translationAvailable = sse_decode_bool(deserializer);
    return MobileCapabilities(
      deviceId: var_deviceId,
      deviceName: var_deviceName,
      platform: var_platform,
      asrAvailable: var_asrAvailable,
      azookeyAvailable: var_azookeyAvailable,
      translationAvailable: var_translationAvailable,
    );
  }

  @protected
  MobileStageResult sse_decode_mobile_stage_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_messageType = sse_decode_String(deserializer);
    var var_sessionId = sse_decode_String(deserializer);
    var var_turnId = sse_decode_u_64(deserializer);
    var var_revision = sse_decode_u_64(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_isFinal = sse_decode_bool(deserializer);
    return MobileStageResult(
      messageType: var_messageType,
      sessionId: var_sessionId,
      turnId: var_turnId,
      revision: var_revision,
      text: var_text,
      isFinal: var_isFinal,
    );
  }

  @protected
  PairRequest sse_decode_pair_request(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_token = sse_decode_String(deserializer);
    var var_deviceId = sse_decode_String(deserializer);
    var var_deviceName = sse_decode_String(deserializer);
    return PairRequest(
      token: var_token,
      deviceId: var_deviceId,
      deviceName: var_deviceName,
    );
  }

  @protected
  PipelineRoute sse_decode_pipeline_route(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_asr = sse_decode_execution_device(deserializer);
    var var_azookey = sse_decode_execution_device(deserializer);
    var var_translation = sse_decode_execution_device(deserializer);
    return PipelineRoute(
      asr: var_asr,
      azookey: var_azookey,
      translation: var_translation,
    );
  }

  @protected
  ProcessingStage sse_decode_processing_stage(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ProcessingStage.values[inner];
  }

  @protected
  SessionConfiguration sse_decode_session_configuration(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_String(deserializer);
    var var_route = sse_decode_pipeline_route(deserializer);
    var var_capabilities = sse_decode_mobile_capabilities(deserializer);
    return SessionConfiguration(
      sessionId: var_sessionId,
      route: var_route,
      capabilities: var_capabilities,
    );
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_azoo_key_model(AzooKeyModel self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_azoo_key_output(
    AzooKeyOutput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.text, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_mobile_capabilities(
    MobileCapabilities self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_mobile_capabilities(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_pipeline_route(
    PipelineRoute self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_pipeline_route(self, serializer);
  }

  @protected
  void sse_encode_desktop_command(
    DesktopCommand self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case DesktopCommand_SessionReady(
        sessionId: final sessionId,
        route: final route,
      ):
        sse_encode_i_32(0, serializer);
        sse_encode_String(sessionId, serializer);
        sse_encode_box_autoadd_pipeline_route(route, serializer);
      case DesktopCommand_ConfigureRoute(route: final route):
        sse_encode_i_32(1, serializer);
        sse_encode_box_autoadd_pipeline_route(route, serializer);
      case DesktopCommand_StartAudio(
        sessionId: final sessionId,
        turnId: final turnId,
        revision: final revision,
      ):
        sse_encode_i_32(2, serializer);
        sse_encode_String(sessionId, serializer);
        sse_encode_u_64(turnId, serializer);
        sse_encode_u_64(revision, serializer);
      case DesktopCommand_EndAudio(
        sessionId: final sessionId,
        turnId: final turnId,
        revision: final revision,
      ):
        sse_encode_i_32(3, serializer);
        sse_encode_String(sessionId, serializer);
        sse_encode_u_64(turnId, serializer);
        sse_encode_u_64(revision, serializer);
      case DesktopCommand_RunAzookey(
        sessionId: final sessionId,
        turnId: final turnId,
        revision: final revision,
        text: final text,
        isFinal: final isFinal,
      ):
        sse_encode_i_32(4, serializer);
        sse_encode_String(sessionId, serializer);
        sse_encode_u_64(turnId, serializer);
        sse_encode_u_64(revision, serializer);
        sse_encode_String(text, serializer);
        sse_encode_bool(isFinal, serializer);
      case DesktopCommand_RunTranslation(
        sessionId: final sessionId,
        turnId: final turnId,
        revision: final revision,
        sourceText: final sourceText,
        isFinal: final isFinal,
      ):
        sse_encode_i_32(5, serializer);
        sse_encode_String(sessionId, serializer);
        sse_encode_u_64(turnId, serializer);
        sse_encode_u_64(revision, serializer);
        sse_encode_String(sourceText, serializer);
        sse_encode_bool(isFinal, serializer);
      case DesktopCommand_StopSession(sessionId: final sessionId):
        sse_encode_i_32(6, serializer);
        sse_encode_String(sessionId, serializer);
      case DesktopCommand_SetTranslationEnabled(enabled: final enabled):
        sse_encode_i_32(7, serializer);
        sse_encode_bool(enabled, serializer);
      case DesktopCommand_Ping(nonce: final nonce):
        sse_encode_i_32(8, serializer);
        sse_encode_u_64(nonce, serializer);
    }
  }

  @protected
  void sse_encode_discovery_response(
    DiscoveryResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.nonce, serializer);
    sse_encode_String(self.endpoint, serializer);
    sse_encode_String(self.token, serializer);
  }

  @protected
  void sse_encode_execution_device(
    ExecutionDevice self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_azoo_key_model(
    List<AzooKeyModel> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_azoo_key_model(item, serializer);
    }
  }

  @protected
  void sse_encode_list_pipeline_route(
    List<PipelineRoute> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_pipeline_route(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_mobile_capabilities(
    MobileCapabilities self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.deviceId, serializer);
    sse_encode_String(self.deviceName, serializer);
    sse_encode_String(self.platform, serializer);
    sse_encode_bool(self.asrAvailable, serializer);
    sse_encode_bool(self.azookeyAvailable, serializer);
    sse_encode_bool(self.translationAvailable, serializer);
  }

  @protected
  void sse_encode_mobile_stage_result(
    MobileStageResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.messageType, serializer);
    sse_encode_String(self.sessionId, serializer);
    sse_encode_u_64(self.turnId, serializer);
    sse_encode_u_64(self.revision, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_bool(self.isFinal, serializer);
  }

  @protected
  void sse_encode_pair_request(PairRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.token, serializer);
    sse_encode_String(self.deviceId, serializer);
    sse_encode_String(self.deviceName, serializer);
  }

  @protected
  void sse_encode_pipeline_route(PipelineRoute self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_execution_device(self.asr, serializer);
    sse_encode_execution_device(self.azookey, serializer);
    sse_encode_execution_device(self.translation, serializer);
  }

  @protected
  void sse_encode_processing_stage(
    ProcessingStage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_session_configuration(
    SessionConfiguration self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sessionId, serializer);
    sse_encode_pipeline_route(self.route, serializer);
    sse_encode_mobile_capabilities(self.capabilities, serializer);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
