// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/simple.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AzooKeyOutput dco_decode_azoo_key_output(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  MobileCapabilities dco_decode_box_autoadd_mobile_capabilities(dynamic raw);

  @protected
  PipelineRoute dco_decode_box_autoadd_pipeline_route(dynamic raw);

  @protected
  DesktopCommand dco_decode_desktop_command(dynamic raw);

  @protected
  DiscoveryResponse dco_decode_discovery_response(dynamic raw);

  @protected
  ExecutionDevice dco_decode_execution_device(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<PipelineRoute> dco_decode_list_pipeline_route(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MobileCapabilities dco_decode_mobile_capabilities(dynamic raw);

  @protected
  MobileStageResult dco_decode_mobile_stage_result(dynamic raw);

  @protected
  PairRequest dco_decode_pair_request(dynamic raw);

  @protected
  PipelineRoute dco_decode_pipeline_route(dynamic raw);

  @protected
  ProcessingStage dco_decode_processing_stage(dynamic raw);

  @protected
  SessionConfiguration dco_decode_session_configuration(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AzooKeyOutput sse_decode_azoo_key_output(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  MobileCapabilities sse_decode_box_autoadd_mobile_capabilities(
    SseDeserializer deserializer,
  );

  @protected
  PipelineRoute sse_decode_box_autoadd_pipeline_route(
    SseDeserializer deserializer,
  );

  @protected
  DesktopCommand sse_decode_desktop_command(SseDeserializer deserializer);

  @protected
  DiscoveryResponse sse_decode_discovery_response(SseDeserializer deserializer);

  @protected
  ExecutionDevice sse_decode_execution_device(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<PipelineRoute> sse_decode_list_pipeline_route(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MobileCapabilities sse_decode_mobile_capabilities(
    SseDeserializer deserializer,
  );

  @protected
  MobileStageResult sse_decode_mobile_stage_result(
    SseDeserializer deserializer,
  );

  @protected
  PairRequest sse_decode_pair_request(SseDeserializer deserializer);

  @protected
  PipelineRoute sse_decode_pipeline_route(SseDeserializer deserializer);

  @protected
  ProcessingStage sse_decode_processing_stage(SseDeserializer deserializer);

  @protected
  SessionConfiguration sse_decode_session_configuration(
    SseDeserializer deserializer,
  );

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_azoo_key_output(AzooKeyOutput self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_mobile_capabilities(
    MobileCapabilities self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_pipeline_route(
    PipelineRoute self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_desktop_command(
    DesktopCommand self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_discovery_response(
    DiscoveryResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_execution_device(
    ExecutionDevice self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_pipeline_route(
    List<PipelineRoute> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mobile_capabilities(
    MobileCapabilities self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mobile_stage_result(
    MobileStageResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pair_request(PairRequest self, SseSerializer serializer);

  @protected
  void sse_encode_pipeline_route(PipelineRoute self, SseSerializer serializer);

  @protected
  void sse_encode_processing_stage(
    ProcessingStage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_session_configuration(
    SessionConfiguration self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
