// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'simple.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `bounded_required_text`, `convert_azookey_input`, `decode_dictionary_bytes`, `decode_wire`, `desktop_envelope`, `device_id`, `encode_desktop_message`, `encode_route_message`, `encode`, `quickmt_config`, `quickmt_options`, `required`, `supported_owner`, `validate_mobile_capabilities`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ActiveAzooKeyVerifier`, `MobileQuickMtEngine`, `MobileRustAsrEngine`, `WireEnvelope`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `convert_azookey_hiragana`

PipelineRoute defaultPipelineRoute() =>
    RustLib.instance.api.crateApiSimpleDefaultPipelineRoute();

AzooKeyModel defaultAzookeyModel() =>
    RustLib.instance.api.crateApiSimpleDefaultAzookeyModel();

List<AzooKeyModel> allAzookeyModels() =>
    RustLib.instance.api.crateApiSimpleAllAzookeyModels();

List<PipelineRoute> allPipelineRoutes() =>
    RustLib.instance.api.crateApiSimpleAllPipelineRoutes();

String pipelineRouteId({required PipelineRoute route}) =>
    RustLib.instance.api.crateApiSimplePipelineRouteId(route: route);

ExecutionDevice stageOwner({
  required PipelineRoute route,
  required ProcessingStage stage,
}) => RustLib.instance.api.crateApiSimpleStageOwner(route: route, stage: stage);

bool shouldContinueOnMobile({
  required PipelineRoute route,
  required ProcessingStage completedStage,
}) => RustLib.instance.api.crateApiSimpleShouldContinueOnMobile(
  route: route,
  completedStage: completedStage,
);

String encodePairRequest({
  required String token,
  required String deviceId,
  required String deviceName,
}) => RustLib.instance.api.crateApiSimpleEncodePairRequest(
  token: token,
  deviceId: deviceId,
  deviceName: deviceName,
);

PairRequest decodePairRequest({required String json}) =>
    RustLib.instance.api.crateApiSimpleDecodePairRequest(json: json);

String encodeSessionConfigure({
  required String sessionId,
  required PipelineRoute route,
  required MobileCapabilities capabilities,
}) => RustLib.instance.api.crateApiSimpleEncodeSessionConfigure(
  sessionId: sessionId,
  route: route,
  capabilities: capabilities,
);

SessionConfiguration decodeSessionConfiguration({required String json}) =>
    RustLib.instance.api.crateApiSimpleDecodeSessionConfiguration(json: json);

String encodeSessionReady({
  required String sessionId,
  required PipelineRoute route,
}) => RustLib.instance.api.crateApiSimpleEncodeSessionReady(
  sessionId: sessionId,
  route: route,
);

String encodeRouteConfiguration({required PipelineRoute route}) =>
    RustLib.instance.api.crateApiSimpleEncodeRouteConfiguration(route: route);

String encodeRouteRequest({required PipelineRoute route}) =>
    RustLib.instance.api.crateApiSimpleEncodeRouteRequest(route: route);

PipelineRoute decodeMobileRouteRequest({required String json}) =>
    RustLib.instance.api.crateApiSimpleDecodeMobileRouteRequest(json: json);

String encodeAudioBoundary({
  required String messageType,
  required String sessionId,
  required BigInt turnId,
  required BigInt revision,
}) => RustLib.instance.api.crateApiSimpleEncodeAudioBoundary(
  messageType: messageType,
  sessionId: sessionId,
  turnId: turnId,
  revision: revision,
);

String encodeStageRequest({
  required String messageType,
  required String sessionId,
  required BigInt turnId,
  required BigInt revision,
  required String text,
  required bool isFinal,
}) => RustLib.instance.api.crateApiSimpleEncodeStageRequest(
  messageType: messageType,
  sessionId: sessionId,
  turnId: turnId,
  revision: revision,
  text: text,
  isFinal: isFinal,
);

MobileStageResult decodeMobileStageResult({required String json}) =>
    RustLib.instance.api.crateApiSimpleDecodeMobileStageResult(json: json);

String encodeTranslationEnabled({
  required String sessionId,
  required bool enabled,
}) => RustLib.instance.api.crateApiSimpleEncodeTranslationEnabled(
  sessionId: sessionId,
  enabled: enabled,
);

DesktopCommand decodeDesktopCommand({required String json}) =>
    RustLib.instance.api.crateApiSimpleDecodeDesktopCommand(json: json);

String encodeStageResult({
  required ProcessingStage stage,
  required String sessionId,
  required BigInt turnId,
  required BigInt revision,
  required String text,
  required bool isFinal,
}) => RustLib.instance.api.crateApiSimpleEncodeStageResult(
  stage: stage,
  sessionId: sessionId,
  turnId: turnId,
  revision: revision,
  text: text,
  isFinal: isFinal,
);

String encodeDiscoveryRequest({required BigInt nonce}) =>
    RustLib.instance.api.crateApiSimpleEncodeDiscoveryRequest(nonce: nonce);

Future<BigInt> decodeDiscoveryRequest({required String json}) =>
    RustLib.instance.api.crateApiSimpleDecodeDiscoveryRequest(json: json);

Future<String> encodeDiscoveryResponse({
  required BigInt nonce,
  required String endpoint,
  required String token,
}) => RustLib.instance.api.crateApiSimpleEncodeDiscoveryResponse(
  nonce: nonce,
  endpoint: endpoint,
  token: token,
);

DiscoveryResponse decodeDiscoveryResponse({required String json}) =>
    RustLib.instance.api.crateApiSimpleDecodeDiscoveryResponse(json: json);

Future<void> initializeAzookeyDictionary({required List<int> bytes}) => RustLib
    .instance
    .api
    .crateApiSimpleInitializeAzookeyDictionary(bytes: bytes);

Future<void> releaseAzookeyDictionary() =>
    RustLib.instance.api.crateApiSimpleReleaseAzookeyDictionary();

Future<void> prepareAzookeyModel({
  required AzooKeyModel model,
  required String modelPath,
  required String tokenizerDirectory,
}) => RustLib.instance.api.crateApiSimplePrepareAzookeyModel(
  model: model,
  modelPath: modelPath,
  tokenizerDirectory: tokenizerDirectory,
);

Future<void> releaseAzookeyModel() =>
    RustLib.instance.api.crateApiSimpleReleaseAzookeyModel();

Future<void> prepareMobileRustAsr({required String modelDirectory}) => RustLib
    .instance
    .api
    .crateApiSimplePrepareMobileRustAsr(modelDirectory: modelDirectory);

Future<String> transcribeMobileRustAsr({required List<int> pcm16}) =>
    RustLib.instance.api.crateApiSimpleTranscribeMobileRustAsr(pcm16: pcm16);

Future<void> releaseMobileRustAsr() =>
    RustLib.instance.api.crateApiSimpleReleaseMobileRustAsr();

Future<void> prepareQuickmtTranslation({required String modelDirectory}) =>
    RustLib.instance.api.crateApiSimplePrepareQuickmtTranslation(
      modelDirectory: modelDirectory,
    );

Future<String> translateQuickmt({required String text}) =>
    RustLib.instance.api.crateApiSimpleTranslateQuickmt(text: text);

Future<void> releaseQuickmtTranslation() =>
    RustLib.instance.api.crateApiSimpleReleaseQuickmtTranslation();

Future<AzooKeyOutput> convertAzookey({required String reading}) =>
    RustLib.instance.api.crateApiSimpleConvertAzookey(reading: reading);

enum AzooKeyModel {
  small,
  xsmall,
}

class AzooKeyOutput {
  final String text;

  const AzooKeyOutput({
    required this.text,
  });

  @override
  int get hashCode => text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AzooKeyOutput &&
          runtimeType == other.runtimeType &&
          text == other.text;
}

@freezed
sealed class DesktopCommand with _$DesktopCommand {
  const DesktopCommand._();

  const factory DesktopCommand.sessionReady({
    required String sessionId,
    required PipelineRoute route,
  }) = DesktopCommand_SessionReady;
  const factory DesktopCommand.configureRoute({
    required PipelineRoute route,
  }) = DesktopCommand_ConfigureRoute;
  const factory DesktopCommand.startAudio({
    required String sessionId,
    required BigInt turnId,
    required BigInt revision,
  }) = DesktopCommand_StartAudio;
  const factory DesktopCommand.endAudio({
    required String sessionId,
    required BigInt turnId,
    required BigInt revision,
  }) = DesktopCommand_EndAudio;
  const factory DesktopCommand.runAzookey({
    required String sessionId,
    required BigInt turnId,
    required BigInt revision,
    required String text,
    required bool isFinal,
  }) = DesktopCommand_RunAzookey;
  const factory DesktopCommand.runTranslation({
    required String sessionId,
    required BigInt turnId,
    required BigInt revision,
    required String sourceText,
    required bool isFinal,
  }) = DesktopCommand_RunTranslation;
  const factory DesktopCommand.stopSession({
    required String sessionId,
  }) = DesktopCommand_StopSession;
  const factory DesktopCommand.setTranslationEnabled({
    required bool enabled,
  }) = DesktopCommand_SetTranslationEnabled;
  const factory DesktopCommand.ping({
    required BigInt nonce,
  }) = DesktopCommand_Ping;
}

class DiscoveryResponse {
  final BigInt nonce;
  final String endpoint;
  final String token;

  const DiscoveryResponse({
    required this.nonce,
    required this.endpoint,
    required this.token,
  });

  @override
  int get hashCode => nonce.hashCode ^ endpoint.hashCode ^ token.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiscoveryResponse &&
          runtimeType == other.runtimeType &&
          nonce == other.nonce &&
          endpoint == other.endpoint &&
          token == other.token;
}

enum ExecutionDevice {
  desktop,
  mobile,
}

class MobileCapabilities {
  final String deviceId;
  final String deviceName;
  final String platform;
  final bool asrAvailable;
  final bool azookeyAvailable;
  final bool translationAvailable;

  const MobileCapabilities({
    required this.deviceId,
    required this.deviceName,
    required this.platform,
    required this.asrAvailable,
    required this.azookeyAvailable,
    required this.translationAvailable,
  });

  Future<PipelineRoute> constrain({required PipelineRoute route}) => RustLib
      .instance
      .api
      .crateApiSimpleMobileCapabilitiesConstrain(that: this, route: route);

  Future<bool> supports({required ProcessingStage stage}) => RustLib
      .instance
      .api
      .crateApiSimpleMobileCapabilitiesSupports(that: this, stage: stage);

  @override
  int get hashCode =>
      deviceId.hashCode ^
      deviceName.hashCode ^
      platform.hashCode ^
      asrAvailable.hashCode ^
      azookeyAvailable.hashCode ^
      translationAvailable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MobileCapabilities &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          deviceName == other.deviceName &&
          platform == other.platform &&
          asrAvailable == other.asrAvailable &&
          azookeyAvailable == other.azookeyAvailable &&
          translationAvailable == other.translationAvailable;
}

class MobileStageResult {
  final String messageType;
  final String sessionId;
  final BigInt turnId;
  final BigInt revision;
  final String text;
  final bool isFinal;

  const MobileStageResult({
    required this.messageType,
    required this.sessionId,
    required this.turnId,
    required this.revision,
    required this.text,
    required this.isFinal,
  });

  @override
  int get hashCode =>
      messageType.hashCode ^
      sessionId.hashCode ^
      turnId.hashCode ^
      revision.hashCode ^
      text.hashCode ^
      isFinal.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MobileStageResult &&
          runtimeType == other.runtimeType &&
          messageType == other.messageType &&
          sessionId == other.sessionId &&
          turnId == other.turnId &&
          revision == other.revision &&
          text == other.text &&
          isFinal == other.isFinal;
}

class PairRequest {
  final String token;
  final String deviceId;
  final String deviceName;

  const PairRequest({
    required this.token,
    required this.deviceId,
    required this.deviceName,
  });

  @override
  int get hashCode => token.hashCode ^ deviceId.hashCode ^ deviceName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PairRequest &&
          runtimeType == other.runtimeType &&
          token == other.token &&
          deviceId == other.deviceId &&
          deviceName == other.deviceName;
}

class PipelineRoute {
  final ExecutionDevice asr;
  final ExecutionDevice azookey;
  final ExecutionDevice translation;

  const PipelineRoute({
    required this.asr,
    required this.azookey,
    required this.translation,
  });

  @override
  int get hashCode => asr.hashCode ^ azookey.hashCode ^ translation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PipelineRoute &&
          runtimeType == other.runtimeType &&
          asr == other.asr &&
          azookey == other.azookey &&
          translation == other.translation;
}

enum ProcessingStage {
  asr,
  azookey,
  translation,
}

class SessionConfiguration {
  final String sessionId;
  final PipelineRoute route;
  final MobileCapabilities capabilities;

  const SessionConfiguration({
    required this.sessionId,
    required this.route,
    required this.capabilities,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^ route.hashCode ^ capabilities.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionConfiguration &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          route == other.route &&
          capabilities == other.capabilities;
}
